# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@main
    - name: Force Xcode 14
      run: sudo xcode-select -switch /Applications/Xcode_14.app
    - name: Run tests
      run: xcodebuild clean test -project "MovieApp.xcodeproj" -scheme "MovieApp" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
    - name: Build App
      run: xcodebuild -project "MovieApp.xcodeproj" -scheme "MovieApp" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
